version: '3'
services:
  pgsqldb:
    image: postgres
    env_file:
      - database.env 
    ports:
      - '5432:5432'
    hostname: pgsqldb
    container_name: pgsqldb
    networks:
      - network-tenpo
  redisdb:
    image: 'bitnami/redis:latest'
    hostname: redisdb
    container_name: redisdb
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - network-tenpo
  backendmock:
    image:  "oscarygutierrezg/test-tenpo-backend-mock"
    hostname: backendmock
    container_name: backendmock
    ports:
      - "8081:8081"
    networks:
      - network-tenpo
  backend:
    image:  "oscarygutierrezg/test-tenpo-backend"
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - pgsqldb
      - redisdb
      - backendmock
    restart: always
    networks:
      - network-tenpo
networks:
  network-tenpo:
    driver: bridge
